name: update ffmpeg
on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * *'  # 15:00 UTC everyday

jobs:
  update-formula:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git
        uses: Homebrew/actions/git-user-config@main

      - name: Update formula
        run: |
          mkdir -p Formula
          ./.github/scripts/update-ffmpeg.sh
          ./.github/scripts/update-ffmpeg-static.sh
          git add ./Formula/ffmpeg.rb ./Formula/ffmpeg-static.rb
          git commit -m 'Updated FFmpeg'
          git push origin main
