name: update ffmpeg
on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * *'  # 15:00 UTC everyday

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git
        uses: Homebrew/actions/git-user-config@main

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update formula
        run: |
          mkdir -p Formula

          sh ./.github/scripts/update-ffmpeg.sh

          git config --global user.name 'Mizuki Nguyen'
          git config --global user.email '49761211+MagicalDrizzle@users.noreply.github.com'
          git commit -m 'Updated FFmpeg to $VERSION'
          git push origin master
